name: faltool
description: A new Flutter package project.
version: 1.0.13
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #PLATFORM: All
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  share_plus: ^11.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  ansicolor: ^2.0.3
  uuid: ^4.5.1
  logger: ^2.5.0
  stack_trace: ^1.12.1
  dartx: ^1.2.0
  rxdart: ^0.28.0
  enum_to_string: ^2.2.1
  fpdart: ^1.1.1
  version: ^3.0.2
  crypto: ^3.0.6
  url_strategy: ^0.3.0
  timeago: ^3.7.0
  numeral: ^3.1.0
  money_formatter: ^0.0.6
  shared_preferences: ^2.5.3
  retry: ^3.1.2

  #PLATFORM: Android, iOS, Linux, MacOS, Windows
  path_provider: ^2.1.5
  universal_io: ^2.2.2

  #PLATFORM: Android, iOS, MacOS, Web
#  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0