name: falconnect
description: A new Flutter package project.
version: 1.3.6
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  faltool:
    path: ../faltool
  falmodel:
    path: ../falmodel

  #PLATFORM: All
  ansicolor: ^2.0.3
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  web_socket_channel: ^3.0.3
  connectivity_plus: ^6.1.4
  dio_cache_interceptor: ^4.0.3
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.3
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
