name: falkit
description: A new Flutter package project.
version: 1.1.7
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  faltool:
    path: ../faltool

  #PLATFORM: All
  gap: ^3.0.1
  flutter_svg: ^2.1.0
  extended_image: ^10.0.1
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

